
<?php
// module/User/view/User/User/index.phtml:

$title = 'Profile';
$this->headTitle($title);
?>
<h3><?= $data->firstName . '&nbsp;' .$data->lastName .'\'s&nbsp;';?><?= $this->escapeHtml($title) ?></h3>
<p>
	<?= $this->flashMessenger()->render('info'); ?>
	<?php 
	if($this->acl->isAllowed($this->user, $data, 'edit')) {
	?>
    <a class="btn btn-primary" href="<?= $this->url('profile', ['action' => 'edit', 'id' => $this->user->id]) ?>" role="button">Edit Profile</a>
	<?php 
	}
	?>
</p>
<div class="container">
  <div class="row">
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
  </div>
</div>