<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Fire MVC Content Management System</h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="http://FireCMS.net/FireCMS" target="_blank">Fire CMS</a>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on Fire CMS.
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/Darksokiller/FireCMS" target="_blank">
        Check FireCMS on GitHub &raquo;
    </a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Follow Development</h2>
        <div class="card-body">
            <p>
                FireCMS CMS is a private project that is being actively developed by
                fireevolve Data Systems LLC. 
            </p>

            <a class="btn btn-primary" href="http://FireCMS.net/FireCMS/portal" target="_blank">FireCMS Project Portal &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Discover Modules</h2>
        <div class="card-body">
            <p>
                FireCMS CMS is a modular application.
                Aurora ships with base functionality to handle nearly everything you may need to do
                on the average website. If by chance the functionality is not in the default build our
                development team can handle any use case. Feel free to contact us!!!
            </p>

            <a class="btn btn-primary" href="http://fireevolve.com/FireCMS/modules" target="_blank">
                FireCMS Modules &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Help &amp; Support</h2>
        <div class="card-body">
            <p>
                If you need any help or support while developing with FireCMS,
                you may reach us via email @ support@fireevolve.com
            </p>
        </div>
    </div>
</div>